---
title: "How to make a blogpost - a brief introduction"
description: |
 Learn how to contribute to the wiki section of the Ecological Department webpage. If you think you have an important information, script, package or just a pieace of code that might be intersesting for your collegues you can create easily a blog post and add this to the wiki section of the webpage.
categories:
  - tutorial
  - workflow
author:
  - name: Moritz Wenzler-Meya
    affiliation: IZW Berlin
    affiliation_url: https://ecodynizw.github.io/EcoDynIZW
date: yyyy-mm-dd
output:
  distill::distill_article:
    self_contained: false
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

- why contributing?
  You have a nice peace of code? You made a cool package?

- how to contribute?
  You have to fork the EcoDynIZW repository, create a post by using the _post_template.rmd and make a merge request when done.

- Please check before for spelling mistakes and if the knitting is working easily, because sometimes we have to rerun the knitting.


```{r install, eval=3}

```

```{r example}

```

```{r plot, echo=FALSE}

```

