---
title: "Categories in Raster Data"
description: |
  Learn how to work with categorial raster data and how to transform the rastervalues into a numerical values.   
categories:
  - terra
  - raster
  - spatial
  - tutorial
author:
  - name: Aimara Planillo & Moritz Wenzler-Meya
    affiliation: IZW Berlin
    affiliation_url: https://ecodynizw.github.io/EcoDynIZW
date: 2023-11-09
output:
  distill::distill_article:
    self_contained: false
    toc: true
draft: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) ## keep this, add other settings if needed
```



```{r install}
library(terra)
```



```{r dummy data, eval=FALSE}
ras <- rast(matrix(rep(c("a", "b", "c"), each = 3), nrow = 3, ncol = 3))

ras

as.data.frame(cats(ras))

plot(ras)
```

lets say you want to reclassify the data, you can add another column by using this:

```{r reclass table, echo=FALSE}
recl_df <- data.frame(value = c(1,2,3),
                      label = c("a", "b", "c"),
                      new_label = c("d", "e", "f"))

ras_new_cat <- categories(ras, 
                          layer = 1, 
                          value = recl_df, 
                          active = 2) # column 2 (do not count the value column! It has to be numeric)

plot(ras_new_cat)
```

Let's say we want to reclassify the spatRaster with a numeric value, we have to take one more step 

```{r reclassify}
recl_df_num <- data.frame(value = c(1,2,3),
                      label = c("a", "b", "c"),
                      new_label = c("d", "e", "f"),
                      new_value = c(4, 5, 6))

ras_new_cat_2 <- categories(ras, 
                          layer = 1, 
                          value = recl_df_num, 
                          active = 3) # column 2 (do not count the value column! It has to be numeric)

plot(ras_new_cat_2)

ras_new_num <- catalyze(ras_new_cat_2)

ras_new_num <- ras_new_num$new_value

plot(ras_new_num, type = "continuous")
```

