---
title: "Geodata"
site: distill::distill_website
output:
distill::distill_article:
  toc: true
  toc_depth: 3
---

# install

```{r}
sapply(list("sf", "tidyverse", "here", "leaflet", "d6geodata", "terra"), 
       library, character.only = TRUE, logical.return = TRUE)
```



```{r, echo = FALSE}
data_list <- list.files("E:/PopDynCloud/GeoData",
                        pattern = "_interactive.rds",
                        full.names = TRUE,
                        recursive = TRUE)

data <- tibble(data_name = unlist(lapply(data_list,
                                  function(x){str_split(x, pattern = "/")[[1]][6]})),
               path = unlist(data_list),
               region = unlist(lapply(data_list,
                               function(x){str_split(str_split(x, pattern = "/")[[1]][6], 
                                   pattern = "_")[[1]][2]}))) |> 
  group_by(data_name) |> 
  mutate(path_tif = gsub(pattern = "_tif_interactive.rds$", replacement = ".tif", x = path))


```

# test plot

```{r}
 map <- leaflet::leaflet() #|> 
leaflet::addProviderTiles(leaflet::providers$CartoDB.Positron)

for (i in 1:nrow(data)) {
      map <- map |> 
        leaflet::addRasterImage(
          x = rast(data$path_tif[i]) |> aggregate(10) |> project("epsg:4326"), group = as.character(data$data_name[i]),
          maxBytes = 16 * 1024 * 1024
          )
    }

map <- map |>
    leaflet::addLayersControl(
      overlayGroups = data$data_name,
      options = leaflet::layersControlOptions(collapsed = FALSE)) |>
    leaflet:: hideGroup(data$data_name[-1]) #hide all groups except the 1st one
```


```{r}
saveRDS(map, here("test_map.rds"))
```



