---
title: "Impressum"
description: ""
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

**Anbieter**

Leibniz-Institut für Zoo- und Wildtierforschung (Leibniz-IZW) im Forschungsverbund Berlin e.V.
Alfred-Kowalke-Str. 17
10315 Berlin, Deutschland


**Adresse**

Leibniz-Institut für Zoo- und Wildtierforschung (Leibniz-IZW) im Forschungsverbund Berlin e.V.
Alfred-Kowalke-Str. 17
10315 Berlin, Deutschland
Tel: +49(0)30 51680
Fax: +49(0)30 5126104


**Redaktion**

Stephanie Kramer-Schadt, Leibniz-Institut für Zoo- und Wildtierforschung (Leibniz-IZW)


**Kontakt**

Tel: +49(0)30 5168- 714
E-mail: kramer[at]izw-berlin.de 


**Vereinsregister**

Der Forschungsverbund Berlin ist im Vereinsregister des Amtsgerichts Berlin-Charlottenburg unter der Registernummer VR 12174 B eingetragen.


**Vertreter**

Der Forschungsverbund Berlin e.V. wird durch den Geschäftsführer Martin Böhnke gemeinsam mit dem Sprecher des Vorstands und bei institutsspezifischen Geschäften mit dem Direktor des betreffenden Instituts vertreten.


**Umsatzsteueridentifikationsnummer**

Die Umsatzsteueridentifikationsnummer des Forschungsverbundes Berlin e.V. lautet: DE 136785011


**Rechtliche Hinweise zur Organisationsform**

Der Forschungsverbund Berlin e.V. vereint sieben wissenschaftlich selbstständige Institute.


**Rechtliche Hinweise zur Haftung**

Der Forschungsverbund Berlin e.V. ist um Richtigkeit und Aktualität der auf dieser Internetpräsenz bereitgestellten Informationen bemüht. Trotzdem können Fehler und Unklarheiten nicht vollständig ausgeschlossen werden. Der Forschungsverbund Berlin e.V. übernimmt deshalb keine Gewähr für die Aktualität, Richtigkeit, Vollständigkeit oder Qualität der bereitgestellten Informationen.
Für Schäden materieller oder immaterieller Art, die durch die Nutzung oder Nichtnutzung der dargebotenen Informationen bzw. durch die Nutzung fehlerhafter und unvollständiger Informationen unmittelbar oder mittelbar verursacht werden, haftet der Forschungsverbund Berlin e.V. nicht, sofern ihm nicht nachweislich vorsätzliches oder grob fahrlässiges Verschulden zur Last fällt. Gleiches gilt für kostenlos zum Download bereitgehaltene Software.

Der Forschungsverbund behält sich vor, Teile des Internetangebots oder das gesamte Angebot ohne gesonderte Ankündigung zu verändern, zu ergänzen, zu löschen oder die Veröffentlichung zeitweise oder endgültig einzustellen.
Die Verantwortlichkeit für „fremde Inhalte“, die beispielsweise durch direkte oder indirekte Verknüpfungen (z. B. so genannten „Links“) zu anderen Anbietern bereitgehalten werden, setzt unter anderem positive Kenntnis des rechtswidrigen bzw. strafbaren Inhaltes voraus. „Fremde Inhalte“ sind in geeigneter Weise gekennzeichnet.
Der Forschungsverbund Berlin e.V. hat auf „fremde Inhalte“ keinerlei Einfluss und macht sich diese Inhalte auch nicht zu Eigen. Der Forschungsverbund Berlin e.V. hat keine positive Kenntnis über rechtswidrige oder anstößige Inhalte auf den verknüpften Seiten fremder Anbieter. Sollten auf den verknüpften Seiten fremder Anbieter dennoch rechtswidrige oder anstößige Inhalte enthalten sein, so distanziert sich der Forschungsverbund Berlin e.V. von diesen Inhalten ausdrücklich.
