---
title: "Msc/Bsc Theses 2018"
description: ""
---

**2018**

* Life-history consequences of snare injuries in female spotted hyenas: A long term study in the Serengeti National Park, Tanzania. **Sara Kaidatzi.** <span class='desaturated'>02.05.2018. Diploma thesis. Biologie. Freie Universität Berlin. Benhaiem S, East ML, Hofer H.</span>

* Usage of landscape metrics to predict spatial distribution of mammals in urban areas. **Jessica Thimian.** <span class='desaturated'>04.08.2018. BSc. Biologie. Freie Universität Berlin. Supervision: Gras P, Kramer-Schadt S, Hofer H.</span>

* Monthly home ranges and habitat preferences of raccoons (*Procyon lotor*) in the Uckermark, Germany – a estimation method comparison. **Pedro Mello Rose.** <span class='desaturated'>2018. BSc. Biologie. Freie Universität Berlin. Supervision: Scholz C, Hofer H.</span>

* An occupancy analysis of the ocelot (*Leopardus pardalis*) and its potential preys in Eastern Panama. **Angelica Maria Moreno Sosa.** <span class='desaturated'>09.10.2018. MSc. Universität Bremen. Supervision: Abrams J, Kramer-Schadt S, Marko Rohlfs (U Bremen).</span>

