---
title: "Msc/Bsc Theses 2024"
description: ""
---

**2024**

* Tracking an urban dweller: Red fox movement patterns and energetic costs in a human-dominated landscape. **Julia Bolk**, <span class='desaturated'>2024 MSc. Humboldt Universität zu Berlin, Lebenswissenschaftliche Fakultät, Institut für Biologie. Supervisors: R Krahe (HUB), C. Scholz, S Kramer-Schadt.</span>

* Co-occurrence of red squirrels (**Sciurus vulgaris**) and meso-carnivores in private gardens in Berlin, Germany. **Josefa Vergara**,  <span class='desaturated'>2024 MSc. Geographischen Institut der Humboldt-Universität zu Berlin. Supervisors: Prof. Dr. Tobias Kümmerle (HUB), Dr. Julie Louvrier.</span>

* Which factors influence the risk of receiving conspecific biting wounds in spotted hyenas (*Crocuta crocuta*). **Jana Marie Kühnapfel**, <span class='desaturated'>08.07.2024 BSc. Friedrich-Schiller-Universität Jena. Fakultät für Biowissenschaften. Supervisors: S. Benhaiem, E. White.</span>

* Untersuchung der biologischen Homogenisierung urbaner Lebensräume unter Verwendung bürgerwissenschaftlicher Daten. **Martin Marunczak**, <span class='desaturated'>23.09.2024 BSc. Humboldt Universität, Lebenswissenschaftliche Fakultät, Institut für Biologie. E Heitlinger (HU), S Kramer-Schadt.</span>

* Computerassistierte fotografische Wiedererkennung bei der Zauneidechse (Lacerta agilis). **David Daniel Beckenbauer**, <span class='desaturated'>22.03.2024 BSc. TU Berlin, Fakultät VI, Studiengang 'Ökologie und Umweltplanung'. Supervisors: S Kramer-Schadt, M.-O. Rödel (MfN).</span>

* Foraging habitat selection by barn swallows and house martins in agricultural landscapes. **Nadja Schedensack** , <span class='desaturated'>16.06.2024 MSc. Ecology and Environmental Planning, TU Berlin. Supervisors: S Kramer-Schadt, Wiebke Ullmann (UPotsdam).</span>






