---
title: "Msc/Bsc Theses 2025"
description: ""
---

**2025**

* Ecological and Sociodemographic Factors Influencing the Risk of Receiving Aggressive Acts in Adult Female Spotted Hyenas (*Crocuta crocuta*). **Antonia Laura Schmitt**. <span class='desaturated'>07.10.2025 BSc. Lebenwissenschaftliche Fakultät Institut für Biologie, Humboldt-Universität zu Berlin. Supervisor: Sarah Benhaiem (IZW), Ella White (IZW), Morgane Gicquel (IZW),  Rüdiger Krahe (HU).</span>

* Are red squirrels (*Sciurus vulgaris*) capable of distinguishing between humans as risk, disturbance or resource?. **Celina Last**.  <span class='desaturated'>29.07.2025 BSc. Ökologie und Umweltplanung. Institut für Ökologie der Technischen Universität Berlin. Supervisor: Stephanie Kramer-Schadt (IZW/ TUB), Sinah Drenske (IZW).</span>

* Long-term biodiversity and survival trends in a reed-dwelling breeding bird community. **Marie Klett**. <span class='desaturated'>25.08.2025 BSc. Biologie. Institut für Biologie der Humboldt Universität zu Berlin. Supervisor: Prof. Rüdiger Krahe (HU), Stephanie Kramer-Schadt (IZW/ TUB), Morgane Gicquel (IZW).</span>

* Biodiversität und Vogelschutz im Spannungsfeld erneuerbarer Energien: Auswirkungen von Freiflächen-Photovoltaikanlagen auf Vogelpopulationen“. **Nico Krieger**. <span class='desaturated'>01.09.2025 BSc. Ökologie und Umweltplanung. Institut für Ökologie der Technischen Universität Berlin. Supervisor: Stephanie Kramer-Schadt (IZW/ TUB), Detlev Kelm (K&S Umweltgutachten).</span>

* Evaluating the influence of interspecific and intraspecific interactions on the reproductive success of house martins (*Delichon urbicum*) and barn swallows (*Hirundo rustica*). **Mateo Reyes**, <span class='desaturated'>16.05.2025 MSc. Ecology and Environmental Planning. TU Berlin. Supervisors: S Kramer-Schadt, Wiebke Ullmann (UP).</span>

* Survival of Eurasian red squirrels (*Sciurus vulgaris*) along an urban-rural gradient in Berlin. **Alina Theresa Berger**, <span class='desaturated'>02.06.2025,  BSc. Ecology and Environmental Planning. TU Berlin, supervisors: S Kramer-Schadt, Sinah Drenske.</span>

* The development of social behaviour in juveniles in a population of reintroduced Northern Bald Ibis (*Geronticus eremita*) using social network analysis. **Nikki Pearson**, <span class='desaturated'>29.06.2025,  MSc. Biodiversity, Evolution, and Ecology. FU Berlin, supervisors: T Straka (FUB), S Kramer-Schadt, Sinah Drenske.</span>

* Saisonale Dynamik der Stadtwildtiere: von Tageslicht bis Jahreszeiten. **Sarina Beiter**, <span class='desaturated'>29.01.2025 MSc. Fakultät für Umwelt und Natürliche Ressourcen Umweltwissenschaften | Naturschutz und Landnutzung der Universität Freiburg. Supervisors: Ilse Storch (Universität Freiburg), S Kramer-Schadt.</span>





