---
title: "Msc/Bsc Theses 2019"
description: ""
---

**2019**

* Demography and population viability of the Northern Bald Ibis (*Geronticus eremita*), a reintroduced bird species. **Sinah Drenske.** <span class='desaturated'>04.02.2019. Bsc. Ökologie und Umweltplanung. Technische Universität Berlin. Supervision: Kramer-Schadt S, Radchuk V, Kowarik I (TUB).</span>

* Wolfmanagement in Deutschland – Vergleich der Wolfmanagementpläne der Bundesländer. **Patrick Enders.** <span class='desaturated'>26.09.2019. Bsc. Landschaftsarchitektur und Landschaftsplanung. TU Berlin. Supervision: Heiland S (TUB), Kramer-Schadt S.</span>

* Inwiefern beeinflussen anthropogene Faktoren die Streifgebietsgrößen sowie täglichen Distanzen von Wildschweinen (*Sus scrofa*)? **Elena Wernitz.** <span class='desaturated'>08.08.2019. Bsc. Ökologie und Umweltplanung. TUB. Supervision: Stillfried M, Kramer-Schadt S.</span>

* Predicting community structure in a changing world – a new dynamic agent-based model to simulate multi-species home range behavior. **Marie-Sophie Rohwäder.** <span class='desaturated'>26.02.2019. Msc. Ökologie, Evolution und Naturschutz. Universität Potsdam. Supervision: Kramer-Schadt S, Jeltsch F (UP).</span>

* Assessing patterns of livestock attacks caused by wolf (*Canis lupus*) using sightings and habitat predictions. **Moritz Wenzler.** <span class='desaturated'>26.11.2019. Msc. Global Change Geography. Humboldt-Universität zu Berlin. Kramer-Schadt S, Planillo A, Kümmerle T (HU).</span>

