---
title: "Msc/Bsc Theses"
description: ""
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<div class='highlightbox'>
  We are looking for motivated students interested in questions about **wildlife dynamics and distributions** under global change, **animal behavioral ecology** or advancing **theory in ecology and evolution**. Students should have a strong background in (or the will to learn) R, statistics and modelling. Please contact us for possible thesis subjects and state your skills and interests (e.g., CV, certificates,…) along with the name of one or two references.
  
**Here you'll find a list of [offers](msc-bsc-theses-offers.html)&ensp;for Bachelor and Master theses.**
    
  **For TU Berlin students:** Please consider the [Reader](https://www.static.tu.berlin/fileadmin/www/10002349/pdf-Dateien/ABSOLVENTINNEN_INFOS_Reader_171023.pdf) for the steps necessary to conduct a thesis. Successful attendance of our courses ‘biodiversity dynamics I + II’ , where we teach spatial R, distribution modelling and occupancy modelling, is of advantage.
</div> 
    
  Below, you will find an overview over currently running theses as well as a list of completed theses for your information.

For older Bachelor and Master theses please check here:<br> [2025](msc-bsc-theses-2025.html)&ensp;[2024](msc-bsc-theses-2024.html)&ensp;[2023](msc-bsc-theses-2023.html)&ensp;[2022](msc-bsc-theses-2022.html)&ensp;[2021](msc-bsc-theses-2021.html)&ensp;[2020](msc-bsc-theses-2020.html)&ensp;[2019](msc-bsc-theses-2019.html)&ensp;[2018](msc-bsc-theses-2018.html)<br>

<div class='headerbox'><hbox>Completed Theses in 2026</hbox></div><br>

*  Spatial ecology of alpine chamois (*rupicapra rupicapra l.*) in the Karwendel Alps: Sex-specific, seasonal & interspecific multi scale patterns derived from maxent models. **Leoni Visca**, <span class='desaturated'>25.07.2026 BSc. Ecology and Environmental Planning, TU Berlin (S. Kramer-Schadt, Wibke Peters, LWF).</span>

* Reconstructing vertebrate communities before defaunation in the Central Annamites, Vietnam. **Ahmed M. Baqai**, <span class='desaturated'>20.07.2026 MSc. Ecology and Environmental Planning, TU Berlin (A. Wilting, R. Sollmann, S. Kramer-Schadt).</span>

* How do landscape elements shape the community composition and diversity of flying insects across different spatial scales in a highly industrialised agricultural landscape? **Antonia. M. Katzenstein**, <span class='desaturated'>20.07.2026 BSc. Ecology and Environmental Planning, TU Berlin (S. Kramer-Schadt, Wiebke Ullmann, Univ. Potsdam). </span>

* Effects of tracking devices on the phenotype, demography, and the behaviours of small aerial-foraging passerines. **Pascal Meyer**, <span class='desaturated'>13.07.2026 MSc. Biodiversity, Evolution & Ecology, FU Berlin (M. Grabow, S. Kramer-Schadt, Jonathan Jeschke, FU). </span>

* Impact of avian blood parasite infection and parasitemia on local movement patterns of free-ranging songbirds. **David Beckenbauer**, <span class='desaturated'>09.07.2026 MSc. Ecology and Environmental Planning, TU Berlin (M. Grabow, S. Kramer-Schadt). </span>

* From Binoculars to Bioacoustics: Comparing Classical and Automated Methods in Bird Monitoring. **Florian Ganz**, <span class='desaturated'>06.07.2026 MSc Ecology, Evolution and Conservation. Univ. Potsdam (C. Landgraf, S Kramer-Schadt, F. Jeltsch, UP).</span>

* Impact of Social Networks on Population’s Resilience to Perturbations. **Soualiyou Ngah-nsangou**, <span class='desaturated'>15.06.2026 MSc. University of Montpellier, Quantitative Ecology and Evolution. Supervisor: Sarah Cubaynes, Sarah Benhaiem</span>

* Neophobia and innovative problem-solving in Eurasian red squirrels (*Sciurus vulgaris*) along an urban gradient in Berlin. **Johanna Leona Eul**. <span class='desaturated'>30.01.2026 MSc. Universität Potsdam, Master in Ecology, Evolution and Conservation. Supervisor: Stephanie  Prof Jana Eccard (UP), Sinah Drenske, Conny Landgraf.</span>

* Inference of Animal Behaviour from Relocation Data: A Performance Comparison of Statistical and Machine Learning Methods. **Ender Daldaban**. <span class='desaturated'>03.01.2026 BSc, TU Berlin, Ecology and Environmental Planning. Supervisor: Stephanie Kramer-Schadt, Marius Grabow.</span>










