---
title: "Msc/Bsc Theses 2020"
description: ""
---

**2020**

* A population viability and connectivity analysis for the alpine lynx (*Lynx lynx*) population. **Eva Sanchez Arribas.** <span class='desaturated'>19.11.2020. MSc. Uppsala University, Sweden. Supervision: Kramer-Schadt S, Planillo A, Molinari-Jobin A (KORA).</span>

* Influence of roost site availability on activity of forest-dwelling bats above coniferous forests. **Franziska Röpke.** <span class='desaturated'>15.10.2020. BSc. Ökologie und Umweltplanung. TU Berlin. Supervision: Volker Kelm (K&S Umweltgutachten), Kramer-Schadt S.</span>

* Spatial, temporal and interindividual determinants of wildlife-vehicle collision mortality in spotted hyenas in the Serengeti National Park between 1989 and 2020. **Marwan Naciri.** <span class='desaturated'>25.06.2020. Msc. Master Biosciences École Normale Supérieure (ENS) Lyon, Frankreich. Supervision: Benhaiem S, Gicquel M, Planillo A, East M, Hofer H.</span>

* Using social network analysis on a population of reintroduced Northern Bald Ibis (*Geronticus eremita*) to understand decisions of migratory association. **Sinah Drenske.** <span class='desaturated'>03.08.2020. Msc. Ökologie und Umweltplanung. Technische Universität Berlin. Supervision: Kramer-Schadt S, Radchuk V, Benhaiem S, Landgraf C.</span> **&rarr; Prize for best Master thesis!**

