---
title: "Publications 2022"
description: ""
output: distill::distill_article
---

Find all our publication as PDFs also at [ResearchGate](https://www.researchgate.net/).   
  
For older publications please check here:<br> [2024](publications.html)&ensp;|&ensp;[2023](pubs-2023.html)&ensp;|&ensp;[2021](pubs-2021.html)&ensp;|&ensp;[2020](pubs-2020.html)&ensp;|&ensp;[2019](pubs-2019.html)&ensp;|&ensp;[2018](pubs-2018.html) 

<br>

<div class='headerbox'><hbox>Peer-Reviewed Publications</hbox></div><br>

* **Alexiou I**, Abrams JF, Coudrat CNZ, Nanthavong C, **Nguyen A**, **Niedballa J**, **Wilting A** , **Tilker A** (2022): Camera-trapping reveals new insights in the ecology of three sympatric muntjacs in an overhunted biodiversity hotspot. MAMM BIOL **102**, 489–500. doi:<span>[10.1007/s42991-022-00248-0](https://doi.org/10.1007/s42991-022-00248-0)</span>

* Antunes AC, Montanarin A, Gräbin DM, Erison Carlos dos Santos Monteiro, Fernando Ferreira de Pinho, Guilherme Costa Alvarenga, Jorge Ahumada, ..., **Sollmann R**, ..., Ribeiro MC (2022): AMAZONIA CAMTRAP: A dataset of mammal, bird, and reptile species recorded with camera traps in the Amazon forest. ECOLOGY **103(9)**, e3738. doi:<span>[10.1002/ecy.3738](https://doi.org/10.1002/ecy.3738)</span>

* Appleton MR, Courtiol A, Emerton L, …, **Tilker A**, et al. (2022): Protected area personnel and ranger numbers are insufficient to deliver global expectations. NAT SUSTAIN **5**, 1100–1110. doi:<span>[10.1038/s41893-022-00970-0](https://doi.org/10.1038/s41893-022-00970-0)</span>

* Asad S, Vitalis V, **Guharajan R**, Abrams JF, Lagan P, Kissing J, Sikui J, **Wilting A**, Rödel MO (2022): Variable species but similar amphibian community responses across habitats following reduced impact logging. GLOB ECOL CONSERV **35**, e02061. doi:<span>[10.1016/j.gecco.2022.e02061](https://doi.org/10.1016/j.gecco.2022.e02061)</span>

* Bitariho R, Akampurira E, **Mugerwa B** (2022): Long-term funding of community projects has contributed to mitigation of illegal activities within a premier African protected area, Bwindi impenetrable National Park, Uganda. CONSERV SCI PRACT **4**, e12761. doi:<span>[10.1111/csp2.12761](https://doi.org/10.1111/csp2.12761)</span>

* Bolas EC, **Sollmann R**, Crooks KR, Boydston EE, Shaskey L, Boser CL, Dillon A, Van Vuren DH (2022): Role of microhabitat and temporal activity in facilitating coexistence of endemic carnivores on the California Channel Islands. J MAMMAL **103**, 18-28. doi:<span>[10.1093/jmammal/gyab125](https://doi.org/10.1093/jmammal/gyab125)</span>

* Brieger F, Kämmerle JL, **Hagen R**, Suchant R (2022): Behavioural reactions to oncoming vehicles as a crucial aspect of wildlife-vehicle collision risk in three common wildlife species. ACCID ANAL PREV **168**, 106564. doi:<span>[10.1016/j.aap.2021.106564](https://doi.org/10.1016/j.aap.2021.106564)</span>

* Bruckermann T, Greving H, **Stillfried M**, Schumann A, Brandt M, Harms U (2022): I’m fine with collecting data: Engagement profiles differ depending on scientific activities in an online community of a citizen science project. PLOS ONE 17, e0275785. doi:<span>[10.1371/journal.pone.0275785](https://doi.org/10.1371/journal.pone.0275785)</span>

* Bruckermann T, **Stillfried M**, Straka TM, Harms U (2022): Citizen science projects require agreement: A Delphi study to identify which knowledge on urban ecology is considered relevant from scientists’ and citizens’ perspectives. INT J SCI EDUC B COMMUN PUBLIC ENGAGEM 12, 75–92. doi:<span>[10.1080/21548455.2022.2028925](https://doi.org/10.1080/21548455.2022.2028925)</span>

* **Calderon Quinonez AP**, **Louvrier J**, **Planillo AP**, Araya-Gamboa, D, Arroyo-Arce S, Barrantes-Núñez M, Carazo-Salazar J, Corrales-Gutiérrez D, Doncaster CP, Foster R, García MJ, Garcia-Anleu R, Harmsen B, Hernández-Potosme S, Leonardo R, Trigueros DM, McNab R, Meyer N, Moreno R, Salom-Pérez R, Sauma Rossi A, Thomson I, Thornton D, Urbina Y, Grimm V, **Kramer-Schadt S** (2022): Occupancy models reveal potential of conservation prioritization for Central American jaguars. ANIM CONSERV **25**, 680–691.  doi:<span>[10.1111/acv.12772](https://doi.org/10.1111/acv.12772)</span>

* Cardador L, Tella JL, **Louvrier J**, Anadón JD, Abellán P, Carrete M (2022): Climate matching, anthropogenic factors, and dispersal contribute differentially to the colonisation and extinction of local populations during dynamic avian invasions. DIVERS DISTRIB **28**, 1908– 1921. doi:<span>[10.1111/ddi.13591](https://doi.org/10.1111/ddi.13591)</span>

* Culhane K, **Sollmann R**, White AM, Tarbill GL, Cooper SD, Young HS (2022): Small mammal responses to fire severity mediated by vegetation characteristics and species traits. ECOL EVOL **12**(5), e8918. doi:<span>[10.1002/ece3.8918](https://doi.org/10.1002/ece3.8918)</span>

* **East ML**, **Thierer D**, **Benhaiem S**, **Metzger S**, Hofer H (2022): Infanticide by adult females causes sexual conflict in a female-dominated social mammal. FRONT ECOL EVOL **10**, 860854. doi:<span>[10.3389/fevo.2022.860854](https://doi.org/10.3389/fevo.2022.860854)</span>

* Figueiredo L, **Scherer C**, Cabral JS (2022): Computational notebooks to facilitate writing and improve reproducibility of (ecological) research. PLOS COMPUT BIOL **18**, e1010356. doi:<span>[10.1371/journal.pcbi.1010356](https://doi.org/10.1371/journal.pcbi.1010356)</span>

* Fischer L, Möller Palau-Ribes F, Kipper S, Weiss M, **Landgraf C**, Lierz M (2022): Absence of Mycoplasma spp. in nightingales (*Luscinia megarhynchos*) and blue (*Cyanistes caeruleus*) and great tits (*Parus ma-jor*) in Germany and its potential implication for evolutionary studies in birds. EUR J WILDL RES 68, 2. doi:<span>[10.1007/s10344-021-01554-7](https://doi.org/10.1007/s10344-021-01554-7)</span>

* Fogarty FA, Yen JDL, Fleishman E, **Sollmann R**, Ke A (2022): Multiple-region, N-mixture community models to assess associations of riparian area, fragmentation, and species richness. ECOL APPL **32**(8), e2698. doi:<span>[10.1002/eap.2698](https://doi.org/10.1002/eap.2698)</span>

* **Gicquel M**, **East ML**, Hofer H, **Benhaiem S** (2022): Early-life adversity predicts performance and fitness in a wild social carnivore. J ANIM ECOL **91**, 2074–2086. doi:<span>[10.1111/1365-2656.13785](https://doi.org/10.1111/1365-2656.13785)</span>

* **Gicquel M**, **East ML**, Hofer H, Cubaynes S, **Benhaiem S** (2022): Climate change does not decouple interactions between a central place foraging predator and its migratory prey. ECOSPHERE **13**, e4012. doi:<span>[10.1002/ecs2.4012](https://doi.org/10.1002/ecs2.4012)</span>

* Gorczynski D, Hsieh C, Ahumad J, Akampurira E, Andrianarisoa MH, Espinosa S, Johnson S, Kayijamahe C, Lima MGM, **Mugerwa B**, Rovero F, Salvador J, Santos F, Sheil D, Uzabah, E, Beaudrot L (2022): Human density modulates spatial associations among tropical forest terrestrial mammal species. GLOB CHANG BIOL **28**, 7205–7216. doi:<span>[10.1111/gcb.16434](https://doi.org/10.1111/gcb.16434)</span> 

* **Grabow M**, **Louvrier JLP**, **Planillo A**, Kiefer S, **Drenske S**, **Börner K**, Stillfried M, Hagen R, Kimmig S, Straka TM,  **Kramer-Schadt S** (2022): Data-integration of opportunistic species observations into hierarchical modeling frameworks improves spatial predictions for urban red squirrels. FRONT ECOL EVOL **10**, 881247. doi:<span>[10.3389/fevo.2022.881247](https://doi.org/10.3389/fevo.2022.881247)</span>

* Günther T, **Kramer-Schadt S**, Fuhrmann M,  Belik V (2022): Environmental factors associated with the prevalence of ESBL/AmpC-producing Escherichia coli in wild boar (*Sus scrofa*).
FRONT VET SCI **9**, 980554. doi:<span>[10.3389/fvets.2022.980554](https://doi.org/10.3389/fvets.2022.980554)</span> 

* Hagemann J, Conejero C, **Stillfried M**, Mentaberre G, Castillo-Contreras R, Fickel J, López-Olvera JR (2022): Genetic population structure defines wild boar as an urban exploiter species in Barcelona, Spain. SCI TOTAL ENVIRONM 833, 155126. doi:<span>[10.1016/j.scitotenv.2022.155126](https://doi.org/10.1016/j.scitotenv.2022.155126)</span> 

* **Hagen R**, Ortmann S, Elliger A, & Arnold J (2022): Evidence for a male-biased sex ratio in the offspring of a large herbivore: The role of environmental conditions in the sex ratio variation. ECOL EVOL **12**, e8938. doi:<span>[10.1002/ece3.8938](https://doi.org/10.1002/ece3.8938)</span>

* Hering R, Hauptfleisch M, Jago M, Smith T, **Kramer-Schadt S**, Stiegler J, Blaum N (2022): Don’t stop me now: Managed fence gaps could allow migratory ungulates to track dynamic resources and reduce fence related energy loss. FRONT ECOL EVOL **10**, 907079. doi:<span>[10.3389/fevo.2022.907079](https://doi.org/10.3389/fevo.2022.907079)</span>

* Hering R, Hauptfleisch M, **Kramer-Schadt S**, Stiegler J,  Blaum N (2022): Effects of fences and fence gaps on the movement behavior of three southern African antelope species. FRONT CONSERV SCI **3**, 959423. doi:<span>[10.3389/fcosc.2022.959423](https://doi.org/10.3389/fcosc.2022.959423)</span> 

* **Kalyahe MM**, Hofer H, **East ML** (2022): Do anthropogenic sources of food increase livestock predation in the area surrounding Ruaha National Park? ENVIRON CONSERV **49**, 105-113. doi:<span>[10.1017/S037689292200008X](https://doi.org/10.1017/S037689292200008X)</span>

* Ke A, Sollmann R, Frishkoff LO, Karp DS (2022): A hierarchical N-mixture model to estimate behavioral variation and a case study of Neotropical birds. ECOL APPL **32**, e2632. doi:<span>[10.1002/eap.2632](https://doi.org/10.1002/eap.2632)</span>

* Kitchener A, Hoffmann M, Yamaguchi N, Breitenmoser-Würsten C, **Wilting A** (2022): A system for designating taxonomic certainty in mammals and other taxa. MAMM BIOL **102**, 251-261.  doi:<span>[10.1007/s42991-021-00205-3](https://doi.org/10.1007/s42991-021-00205-3)</span>

* Kitchener AC, Simo FT, **Mugerwa B**, Sanderson JG (2022): Evidence that Temminck described Felis aurata in 1825, not 1827. ARCH NAT HIST **49**, 78-85. doi:<span>[10.3366/anh.2022.0759](https://doi.org/10.3366/anh.2022.0759)</span>

* Krause T, **Tilker A** (2022): How the loss of forest fauna undermines the achievments of the SDG’s. AMBIO **51**, 103–113. doi:<span>[10.1007/s13280-021-01547-5](https://doi.org/10.1007/s13280-021-01547-5)</span>

* **Louvrier J**; **Planillo A**; **Stillfried M**; **Hagen R**; **Boerner K**; **Kimmig S**; Ortmann S; Schumann A; Brandt M; **Kramer-Schadt S** (2021). Spatiotemporal interactions of a novel mesocarnivore community in an urban environment before and during SARS-CoV-2 lockdown. J ANIM ECOL **91**, 367–380. DOI: [10.1111/1365-2656.13635](https://doi.org/10.1111/1365-2656.13635)

* McLaughlin JP, Schroeder J, White AM, Culhane K, Mirts HE, Tarbill GL, Sire L, Page M, Baker E, Moritz M, Brashares J, Young HS, **Sollmann R** (2022): Food webs for three burn severities after wildfire in the Eldorado National Forest, California. NAT SCI DATA **9**, 384. doi:<span>[10.1038/s41597-022-01220-w](https://doi.org/10.1038/s41597-022-01220-w)</span>

* Mirts HE, McLaughlin JP, Weller TJ, White AM, Young HS, **Sollmann R** (2022): Bats in the megafire: assessing species‘ site use in a postfire landscape in the Sierra Nevada. J MAMMAL **103**(1), 111-123. doi:<span>[10.1093/jmammal/gyab129](https://doi.org/10.1093/jmammal/gyab129)</span>

* **Moreno-Sosa AM**, Yacelga M, Craighead K, **Kramer-Schadt S**, **Abrams JF** (2022): Can prey occupancy act as a surrogate for mesopredator occupancy? A case study of ocelot (*Leopardus pardalis*). MAMM BIOL **102**, 163-175, doi:<span>[10.1007/s42991-022-00232-8](https://doi.org/10.1007/s42991-022-00232-8)</span>

* **Nguyen TV**, **Wilting A**, **Niedballa J**, **Nguyen A**, Rawson BM, Nguyen AQH, Cao TT, Wearn OR, Dao AC, **Tilker A** (2022): Getting the big picture: Landscape-scale occupancy patterns of two Annamite endemics among multiple protected areas. CONS SCI PRACT **4**, e620. doi:<span>[10.1111/csp2.620](https://doi.org/10.1111/csp2.620)</span>

* **Niedballa J**, **Axtner J**, Döbert TF, **Tilker A**, **Nguyen A**, **Wong ST**, Fiderer C, Heurich M, & **Wilting A** (2022): imageseg: An R package for deep learning-based image segmentation. METHODS ECOL EVO **13**, 2363– 2371, doi:<span>[10.1111/2041-210X.13984](https://doi.org/10.1111/2041-210X.13984 )</span> 

* Reusch C, Lozar M, **Kramer-Schadt S**, Voigt CC (2022): Coastal onshore wind turbines lead to habitat loss for bats in Northern Germany. J ENV MANAGE **310**. doi:<span>[10.1016/j.jenvman.2022.114715](https://doi.org/10.1016/j.jenvman.2022.114715)</span>

* Ripari L & **Premier J**, Belotti E, Bluhm H, Breitenmoser-Würsten C, Bufka L, Červený J, Drouet-Hoguet N, Fuxjäger C, Jędrze-jewski W, Kont R, Koubek P, Kowalczyk R, Krofel M, Krojerová-Prokešová J, Molinari-Jobin A, Okarma H, Oliveira T, Remm J, Schmidt K, Zimmermann F, **Kramer-Schadt S**, Heurich M (2022): Human disturbance is the most limiting factor driving habitat selection of a large carnivore throughout Continental Europe. BIOL CONS **266**, 109446. doi:<span>[10.1016/j.biocon.2021.109446](https://doi.org/10.1016/j.biocon.2021.109446)</span>

* Semper-Pascual A, Bischof R, Milleret C, Beaudrot L, Vallejo-Vargas AF, Ahumada JA, Bitariho R, Jansen PA, Moreira Lima MG, **Mugerwa B**, Rovero F, Santos F, Sheil D (2022): Occupancy winners in tropical protected forests: a pantropical analysis. PROC R SOC B **289**. doi:<span>[10.1098/rspb.2022.0457](https://doi.org/10.1098/rspb.2022.0457)</span>

* Stiegler J, Lins A, Dammhahn M, **Kramer-Schadt S**, Ortmann S, Blaum N (2022): Personality drives activity and space use in a mammalian herbivore. MOV ECOL **10**, 33. doi:<span>[10.1016/j.biocon.2021.109446](https://doi.org/10.1016/j.biocon.2021.109446)</span>

* Temu SE, Nahonyo CL, **East ML**, Moehlman PD (2022): Diet of the Golden Jackal (*Canis aureus*) and Sil-ver-Backed Jackal (*Canis mesomelas*) in the Southern Part of the Serengeti Ecosystem, Tanzania: A Comparative Study. TANZ J SCI **48**, 773–784. doi:<span>[10.4314/tjs.v48i4.5](https://doi.org/10.4314/tjs.v48i4.5)</span>

* Vallejo-Vargas AF, Sheil D, Semper-Pascual A, Beaudrot L, Ahumada JA, Akampurira E, Bitariho R, Espinosa S, Estienne V, Jansen PA, Kayijamahe C, Martin EH, Lima MGM, **Mugerwa B**, Rovero F, Salvador J, Santos F, Spironello WR, Uzabaho E, Bischof R (2022): Consistent diel activity patterns of forest mammals among tropical regions. NAT COMMUN **13**, 7102.  doi:<span>[10.1038/s41467-022-34825-1](https://doi.org/10.1038/s41467-022-34825-1)</span>

* Vlaschenko A, Kravchenko K, Yatsiuk Y, Hukov V, **Kramer-Schadt S**, **Radchuk V** (2022): Bat assemblages are shaped by land cover types and forest age: A case study from eastern Ukraine. FORESTS **13**, 1732. doi:<span>[10.3390/f13101732](https://doi.org/10.3390/f13101732)</span>

* Voigt CC, **Scherer C**, Runkel V (2022). Modelling the power of acoustic monitoring to predict bat fatalities at wind turbines. CONSERV SCI PRACT **4**, e12841. doi:<span>[10.1111/csp2.12841](https://doi.org/10.1111/csp2.12841)</span>

* **Wilting A**, **Nguyen TV**, **Axtner J**, **Nguyen A**, Schmidt A, Le M, Nguyen AHQ, Rawson BM, **Tilker A**, Fickel J (2022). Creating genetic reference datasets: Indirect sampling of target species using terrestrial leeches as sample “collectors”. EDNA **4**(2), 311-325. DOI: [10.1002/edn3.256](https://doi.org/10.1002/edn3.256)

* **Wong S**, Guharajan R, Petrus A, Jubili J, Lietz R, Abrams J, Hon J, Alen L, Ting N, Wong G, Tchin L, Bijack N, **Kramer-Schadt S**, **Wilting A**, **Sollmann R** (2022): How do terrestrial wildlife communities respond to small-scale Acacia plantations embedded in harvested tropical forest? ECOL EVOL **12**, e9337. doi:<span>[10.1002/ece3.9337](https://doi.org/10.1002/ece3.9337)</span>




<div class='headerbox'><hbox>Preprints</hbox></div><br>

* **Mugerwa B**, **Niedballa J**, **Planillo A**, Sheil D, **Kramer-Schadt S**, **Wilting A** (2022): Global disparity of research allocation and the Aichi biodiversity conservation targets. BIORXIV 2022.04.07.486958, doi:<span>[10.1101/2022.04.07.486958](https://doi.org/10.1101/2022.04.07.486958)</span>


<div class='headerbox'><hbox>Book Chapters & Reports</hbox></div><br>

* Gimenez  O, **Louvrier  J**, Lauret  V,  Santostasi  N (2022): Studying Species Demography and Distribution in Natural Conditions: Hidden Markov Models. In Statistical Approaches for Hidden Variables in Ecology (eds N. Peyrard and O. Gimenez). [https://doi.org/10.1002/9781119902799.ch3](https://doi.org/10.1002/9781119902799.ch3)

* Papaïx J, Soubeyrand S, Bonnefon O, Walker E, **Louvrier J**, Klein E,  Roques L (2022): Inferring Mechanistic Models in Spatial Ecology Using a Mechanistic-Statistical Approach. In Statistical Approaches for Hidden Variables in Ecology (eds N. Peyrard and O. Gimenez). [https://doi.org/10.1002/9781119902799.ch4](https://doi.org/10.1002/9781119902799.ch4)

* Thonicke K, Rahner E, Arneth A, Bartkowski B, Bonn A, Döhler C, Finger R, Freitag J, Grosch R, Grossart H.-P, Grützmacher K, Hartman Scholz A, Häuser C, Hickler T, Hölker F, Jähnig S C, Jeschke J, Kasen R, Kastner T, **Kramer-Schadt S**, Krug C, Lakner S, Loft L, Matzdorf B, Meakins F, De Meester L, Monaghan M T, Müller D, Overmann J, Quaas M, **Radchuk V**, Reyer C, Roos C, Scholz I, Schroer S, Sioen G B, Sommer S, Sommerwerk N, Tockner K, Turk Z, Warner B, Wätzold F, Wende W, Veenstra, van der Voort H (2022): 10 Must-Knows aus der Biodiversitätsforschung 2022 | 10 Must knows from biodiversity science 2022. Leibniz-Forschungsnetzwerk Biodiversität, Potsdam, Deutschland. doi:<span>[10.5281/zenodo.6257476](https://doi.org/10.5281/zenodo.6257476) | [zenodo.org/record/6257527](https://zenodo.org/record/6257527)</span>
