---
title: "Publications 2021"
description: ""
---

<b style='color:red;'>
-> check details
-> add missing publications
</b>


## In Press

<b style='color:red;'>
-> update details  
-> incl. in peer-reviewed
</b>





## 2021

<div class='headerbox'><hbox>Peer-Reviewed Publications</hbox></div><br>

* **Abrams JF**, Sollmann R, Mitchel SL, Struebig MJ, **Wilting A** (2021). Occupancy-based diversity profiles: capturing biodiversity complexities while accounting for imperfect detection. ECOGRAPHY 44(7), 975-986. DOI: [10.1111/ecog.05577](https://doi.org/10.1111/ecog.05577)

* **Alfano N**, Dayaram A, **Axtner J**, Tsangaras K, **Kampmann ML**, **Mohamed A**, **Wong ST**, Gilbert MTP, **Wilting A** & Greenwood AD (in press). Non-invasive surveys of mammalian viruses using environmental DNA. Methods in Ecology and Evolution. DOI: [10.1111/2041-210X.13661](https://doi.org/10.1111/2041-210X.13661)

* Asad S, **Abrams JF**, **Guharajan R**, Lagan P, Kissing J, Sikui J, **Wilting A**, Rödel MO (2021). Amphibian responses to conventional and reduced impact logging. FOR ECOL MANAG 484, 118949. DOI: [10.1016/J.foreco.2021.118949](https://doi.org/10.1016/j.foreco.2021.118949)

* Ayllón D, Augusiak J, Baveco H, Berger U, Charles S, Martin R, Focks A, Galic N, Gallagher C, Liu C, van Loon EE, Nabe-Nielsen J, Piou C, Polhill JG, Preuss TG, **Radchuk V**, Schmolke A, Stadnicka-Michalak J, Thorbek P, Railsback SF & Grimm V (2021). Keeping modelling notebooks with TRACE: good for you and good for environmental research and management support. Environmental Modelling & Software 136:104932. DOI: [10.1016/j.envsoft.2020.104932](https://doi.org/10.1016/j.envsoft.2020.104932)

* Bastianelli ML, **Premier J**, Herrmann M, Anile S, Monterroso P, Kuemmerle T, …, & Heurich M (2021). Survival and cause-specific mortality of European wildcat (*Felis silvestris*) across Europe. Biological Conservation 261:109239. DOI: [j.biocon.2021.109239](https://doi.org/10.1016/j.biocon.2021.109239)

* Bueno de Mesquita CP, Nichols LM, Gebert MJ, Vanderburgh C, Bocksberger G, Lester JD, Kalan AK, Dieguez P, McCarthy MS, Agbor A, Álvarez Varona P, Ayimisin AE, Bessone M, Chancellor R, Cohen H, Coupland C, Deschner T, Egbe VE, Goedmakers A, Granjon A-C, Grueter CC, Head J, R. Hernandez-Aguilar A, Jeffery KJ, Jones S, Kadam P, Kaiser M, Lapuente J, Larson B, Marrocoli S, Morgan D, **Mugerwa B**, Mulindahabi F, Neil E, Niyigaba P, Pacheco L, Piel AK, Robbins MM, Rundus A, Sanz CM, Sciaky L, Sheil D, Sommer V, Stewart FA, Ton E, van Schijndel J, Vergnes V, Wessling EG, Wittig RM, Yuh YG, Yurkiw K, Zuberbühler K, Gogarten JF, Heintz-Buschart A, Muellner-Riehl AN, Boesch C, Kühl HS, Fierer N, Arandjelovic M, Dunn RR. 2021. Structure of Chimpanzee Gut Microbiomes across Tropical Africa. MSYSTEMS 6(3), e01269-20. DOI: [10.1128/mSystems.01269-20](https://doi.org/10.1128/mSystems.01269-20)

* Bruckermann T, Greving H, Schumann A, **Stillfried M**, **Börner K**, **Kimmig SE**, **Hagen R**, Brandt M, Harms U. 2021. To know about science is to love it? Unraveling cause–effect relationships between knowledge and attitudes toward science in citizen science on urban wildlife ecology. Journal of Research in Science Teaching 58, 1179-1202. DOI: [10.1002/tea.21697](https://doi.org/10.1002/tea.21697)

* Chakravarty, R., Mohan, R., Voigt, C.C. , Krishnan, A., **Radchuk, V**. (2021). Functional diversity of Himalayan bat communities declines at high elevation without the loss of phylogenetic diversity. Sci Rep 11, 22556. DOI: [10.1038/s41598-021-01939-3](https://doi.org/10.1038/s41598-021-01939-3)

* Clark AT, Arnoldi J‐F, Zelnik YR, Barabas G, Hodapp D, Karakoç C, König S, **Radchuk V**, Donohue I, Huth A, Jacquet C, de Mazancourt C, Mentges A, Nothaaß D, Shoemaker LG, Taubert F, Wiegand T, Wang S, Chase JM, Loreau M, Harpole S (2021). General statistical scaling laws for stability in ecological systems. ECOL LETT. DOI: [10.1111/ele.13760](https://doi.org/10.1111/ele.13760)

* Dayaram AS, Seeber P, Courtiol A, Soilemetzidou S, Tsangaras K, **Franz M**, McEwen G, Azab W, Kaczensky P, Melzheimer J, **East ML**, Ganbaatar O, Walzer C, Osterrieder N, Greenwood AD (2021). Seasonal host and ecological drivers may promote restricted water as a viral vector. SCI TOTAL ENVIRON 773, 145446. DOI: [10.1016/j.scitotenv.2021.145446](https://doi.org/10.1016/j.scitotenv.2021.145446)

* **Ferreira SCM**, **Veiga MM**, Hofer H, **East ML**, Czirják GÁ (2021). Noninvasively measured immune responses reflect current parasite infections in a wild carnivore and are linked to longevity. ECOL EVOL, early view 11(12), 7685-7699. DOI: [10.1002/ece3.7602](https://doi.org/10.1002/ece3.7602)

* Fischer L, Möller Palau-Ribes F, Kipper S, Weiss M, **Landgraf C**, Lierz M (accepted). Absence of Mycoplasma spp. in nightingales (*Luscinia megarhynchos*) and blue (*Cyanistes caeruleus*) and great tits (*Parus major*) in Germany and its potential implication for evolutionary studies in birds. EUR J WILDL RES 68, 2. DOI: [10.1007/s10344-021-01554-7](https://doi.org/10.1007/s10344-021-01554-7)

* Fischer M, Sutherland D, Coulson G, **Stillfried M**, **Kramer-Schadt S**, di Stefano J (2021). Spatial and temporal responses of swamp wallabies to roads in a human-modified landscape. WILDL BIOL 2021(2), wlb.00691. DOI: [10.2981/wlb.00691](https://doi.org/10.2981/wlb.00691)

* Gray TNE, Belecks M, O’Kelly HJ, Rao M, Roberts O, **Tilker A**, Signs M, Yoganand K (2021). Understanding and solving the South-East Asian snaring crisis. THE ECOLOGICAL CITIZEN 4(2), 129-141. [https://www.ecologicalcitizen.net](https://www.ecologicalcitizen.net)

* **Guharajan R**, **Mohamed A**, **Wong ST**, **Niedballa J**, **Petrus A**, **Jubili J**, **Lietz R**, Clements GR, Wong WM, Kissing J, Lagan P, **Wilting A** (2021). Sustainable forest management is vital for the persistence of sun bear Helarctos malayanus populations in Sabah, Malaysian Borneo. FOR ECOL MANAG 493, 119270. DOI: [10.1016/j.foreco.2021.119270](https://doi.org/10.1016/j.foreco.2021.119270)

* **Hagen R**, Ortmann S, Elliger A & Arnold J (in press). Advanced roe deer (*Capreolus capreolus*) parturition date in response to climate change. Ecosphere 12(11), e03819. DOI: [10.1002/ecs2.3819](https://doi.org/10.1002/ecs2.3819)

* Krause T, **Tilker A** (2021). Defaunation jeopardizes the SDG’s – How the loss of forest fauna undermines the achievements of the SDG’s. AMBIO. DOI: [10.1007/s13280-021-01547-5](https://doi.org/10.1007/s13280-021-01547-5)

* Krücken J, Czirják GÁ, Ramünke S, Maria Serocki, Heinrich SK, Melzheimer J, Costa MC, Hofer H, Aschenborn OHK, Barker NA, Capodanno S, Madeira de Carvalho L, von Samson-Himmelstjerna G, **East ML** & Wachter B (2021). Genetic diversity of vector-borne pathogens in spotted and brown hyenas from Namibia and Tanzania relates to ecological conditions rather than host taxonomy. PARASITES VECTORS 14, 328. DOI: [10.1186/s13071-021-04835-x](https://doi.org/10.1186/s13071-021-04835-x)

* **Kürschner T**, **Scherer C**, **Radchuk V**, Blaum N, **Kramer-Schadt S**. (2021) Movement can mediate temporal mismatches between resource availability and biological events in host-pathogen interactions. ECOL EVOL 11(10), 5728-41. DOI: [10.1002/ece3.7478](https://doi.org/10.1002/ece3.7478)

* **Louvrier J**; **Planillo A**; **Stillfried M**; **Hagen R**; **Boerner K**; **Kimmig S**; Ortmann S; Schumann A; Brandt M; **Kramer-Schadt S** (2021). Spatiotemporal interactions of a novel mesocarnivore community in an urban environment before and during SARS-CoV-2 lockdown. J ANIM ECOL, 00, 1– 14. DOI: [10.1111/1365-2656.13635](https://doi.org/10.1111/1365-2656.13635)

* Malishev M and **Kramer-Schadt S** (2021). Movement, Models, and Metabolism: Individual-based energy budget models as next-generation extensions for predicting animal movement outcomes across scales. ECOL MODELL 441, 109413. DOI: [10.1016/j.ecolmodel.2020.109413](https://doi.org/10.1016/j.ecolmodel.2020.109413)

* **Marescot L**, **Franz M**, **Benhaiem S**, Hofer H, **Scherer C**, **East ML** & **Kramer-Schadt S** (in press). Keeping the kids at home can limit the persistence of contagious pathogens in social animals. Journal of Animal Ecology. DOI: [10.1111/1365-2656.13555](https://doi.org/10.1111/1365-2656.13555).

* **Mohamed A**, Sollmann R, **Wong ST**, **Niedballa J**, **Abrams JF**, Kissing J, **Wilting A** (2021): Counting Sunda clouded leopards with confidence: incorporating individual heterogeneity in density estimates. ORYX 55(1), 56-65. DOI: [10.1017/S0030605318001503](https://doi.org/10.1017/S0030605318001503)

* **Nguyen A**, **Tilker A**, Le D, Le HV, Le SV, Luu TH, Tran BV, **Wilting A** (2021). New records and southern range extension of the Annamite striped rabbit *Nesolagus timminsi* in Vietnam. MAMMALIA, online first. DOI: [10.1515/mammalia-2020-0189](https://doi.org/10.1515/mammalia-2020-0189)

* Nguyen AT, **Tilker A**, **Nguyen TV** & Le M (2021). Camera-trap records of muntjac in the lowlands of Hue Saola Nature Reserve, central Vietnam. DSG Newsletter 32.

* **Nguyen TV**, **Tilker A**, **Nguyen A**, **Hörig L**, **Axtner J**, Schmidt A, Le M, Nguyen AHQ, Rawson BM, **Wilting A**, Fickel J (2021). Using terrestrial leeches to assess the genetic diversity of an elusive species: the Annamite striped rabbit *Nesolagus timminsi*. ENVIRONMENTAL DNA 3, 780-791. DOI: [10.1002/edn3.182](https://doi.org/10.1002/edn3.182)

* **Olarte-Castillo XA**, Dos Remédios JF, Heeger F, Hofer H, **Karl S**, Greenwood AD, **East ML**. The virus-host interface: Molecular interactions of Alphacoronavirus-1 variants from wild and domestic hosts with mammalian aminopeptidase N. MOL ECOL. 2021;30(11):2607-2625. DOI: [10.1111/mec.15910](https://onlinelibrary.wiley.com/doi/abs/10.1111/mec.15910)

* **Planillo A**, **Kramer-Schadt S**, Buchholz S, **Gras P**, von der Lippe M, **Radchuk V**. (2021) Arthropod abundance modulates bird community responses to urbanization. DIV DISTRIB 27(1), 34-49. DOI: [10.1111/ddi.13169](https://onlinelibrary.wiley.com/doi/10.1111/ddi.13169)

* **Planillo A**, Fiechter L, Sturm U, Heucke-Voigt S, **Kramer-Schadt S** (2021) Citizen science data for urban planning: Comparing different sampling schemes for modelling urban bird distribution. LAND URB PLAN 211. DOI: [10.1016/j.landurbplan.2021.104098](https://doi.org/10.1016/j.landurbplan.2021.104098)

* **Premier Jv**, Gahbauer M, Leibl F, Heurich M (2021). In-situ feeding as a new management tool to conserve orphaned Eurasian lynx (*Lynx lynx*). ECOL EVOL, accepted. DOI: [10.1002/ece3.7261](https://doi.org/10.1002/ece3.7261)

* Pretzlaff I, **Radchuk V**, Turner JM, Dausmann KH (2021) Flexibility in thermal physiology and behaviour allows body mass maintenance in hibernating hazel dormice. J ZOOL, 314(1), 1-11. DOI: [10.1111/jzo.12862](https://doi.org/10.1111/jzo.12862)

* Tran DV, Viet DP, Tien TV, **Nguyen A**, Van CP & **Tilker A** (in press). New records of the forest musk deer *Moschus berezovskii* in Viet Nam revealed by camera-traps. ORYX 55(4) , 494-495. DOI: [10.1017/S0030605321000569](https://doi.org/10.1017/S0030605321000569)

* Wikenros C, **Gicquel M**, Zimmermann B, FlagstaO, Akesson M (2021). Age at first reproduction in wolves: different patterns of density dependence for females and males. PRoc R SOC B 288, 2021020. DOI: [10.1098/rspb.2021.0207](https://doi.org/10.1098/rspb.2021.0207)

* **Wilting A**, **Nguyen TV**, **Axtner J**, **Nguyen A**, Schmidt A, Le M, Nguyen AHQ, Rawson BM, **Tilker A**, Fickel J (2022). Creating genetic reference datasets: Indirect sampling of target species using terrestrial leeches as sample “collectors”. ENVIRONMENTAL DNA, 4(2), 311-325. DOI: [10.1002/edn3.256](https://doi.org/10.1002/edn3.256)





<div class='headerbox'><hbox>Preprints</hbox></div><br>

* **Drenske S**, **Radchuk V**, **Scherer C**, Esterer C, Kowarik I, Fritz J & **Kramer-Schadt S** (2021). Halfway to self-sustainability: reintroduced migratory European Northern Bald Ibises (*Geronticus eremita*) still need management interventions for population viability. bioRxiv. DOI: [10.1101/2021.04.03.438331](https://doi.org/10.1101/2021.04.03.438331)

* Hermanns K, Marklewitz M, Zirkel F, Kopp K, **Kramer-Schadt S** & Junglen S (2021). Mosquito community composition shapes virus prevalence patterns along anthropogenic disturbance gradients. bioRXiv. DOI: [10.1101/2021.02.04.429754](https://doi.org/10.1101/2021.02.04.429754)



<div class='headerbox'><hbox>Book Chapters & Reports</hbox></div><br>

* Heurich M, **Premier J**, **Schultze-Naumburg J**, Herdtfelder M, Oeser J & **Kramer-Schadt S** (2021). Erforschung der Populations- und Bewegungsökologie des Luchses als Grundlage eines Metapopulationsmanagements der kontinentaleuropäischen Luchspopulationen (*Lynx lynx*). Natur und Landschaft 96 (1). DOI: [10.17433/1.2021.50153867.1118](https://doi.org/10.17433/1.2021.50153867.1118)

* **Radchuk V**, **Kramer-Schadt S**, Berger U, **Scherer C**, Backmann P & Grimm V (2021). Individual-based models. In: Demographic Methods across the Tree of Life, Salguero-Gomez R & Gamelon M (eds.), Oxford University Press [https://global.oup.com/academic/product/demographic-methods-across-the-tree-of-life-9780198838609?cc=de&lang=en&](https://global.oup.com/academic/product/demographic-methods-across-the-tree-of-life-9780198838609?cc=de&lang=en&).
