---
title: "Biotic and abiotic drivers influence the infections of soil-transmitted helminth infections at the human-livestock-wildlife interface"
description: ""
---

(contact <a href="mailto:pearson@izw-berlin.de">pearson[at]izw-berlin.de</a>)

Soil-transmitted helminths (STH) are parasitic nematodes that mainly spread through soil, where the eggs can also survive for more than 5 years. Controlled studies have shown that the duration of the egg development is influenced by factors such as temperature and moisture. These parasites affect humans, animals and the environment. They negatively affect a host’s health by reducing productivity, growth and development. Recent studies have shown that helminth prevalences have increased in free-range livestock farming compared to conventional farming. Little is known about the affect of farming systems on the transmission risk for local wildlife, like wild boar, or about how climate and environmental factors influence the transmission risk at these livestock-wildlife interfaces.

Also, pathogen occurrence and their prevalence vary across environmental gradients. Extreme land use like urbanisation and agriculture affect wildlife by altering their food source, behaviour, and contact with human pets, and livestock. These interfaces can alter parasite communities for cross-species transmissions as seen in a study by Scholz et al. (2024) where Helminth species richness increased in foxes with lower body weight and during winter and spring. Season and urbanisation also affected community composition. One soil-transmitted helminth, Toxocara canis, was mainly found in male foxes in Berlin, demonstrating that environmental and host factors, including age, weight, and sex, shape helminth distribution.

To understand how Biotic and abiotic drivers influence the infections of soil-transmitted helminth infections at the human-livestock-wildlife interface we aim to:

* 1)	Investigate how various environmental factors influence the prevalence and distribution of soil-transmitted roundworms (e.g., of the order Ascaridida) among wild and livestock animals. These include, for example, the swine roundworm (Ascaris suum), which is transmitted to wild boars, or the large poultry roundworm (Ascaridia galli), the cecal worm (Heterakis gallinarum), and others, which are transmitted to gallinaceous birds, like pheasants, and quails. I expect that the shift toward free-range livestock farming on organic farms will lead to increased transmission of parasites between domestic and wild animals.

* 2)	In a second project, we would like to examine the roundworm community of wild boars in greater detail, and also analyse its prevalence and distribution. In addition, we would like to study the raccoon roundworm (Baylisascaris procyonis) and the dog roundworm (Toxocara canis) in Berlin’s raccoons and foxes. 

We are actively looking for collaborators to help us gather samples from wild boars and other wildlife. To achieve the broadest possible coverage of Germany, we would appreciate help from anyone who is interested.  
What does this mean for you?  You would need to collect samples for us while carrying out your own work—whether that involves sample collection, hunting, telemetry work, or working with sedated animals. We would send you sampling kits with all the needed materials and a sampling collection protocol so that your workload is kept to a minimum.   

Through your help, we would gain a broad coverage of Germany. In return we offer first hand info on prevalences in your samples and co-authorship for major contributions.
