---
title: "Teaching"
description: ""
output:
distill::distill_article:
  toc: true
  toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Course collection

Welcome to the course collection we have developed at our Department. Below you will find the compilation of our courses. These are hosted within one repository, so that data can be shared between the courses.
<br>
The courses follow a logic order. The first introductory courses give an overview over handling data in R; we then introduce statistical analyses for various types of data, e.g. from spatial distribution models of single species via biodiversity analyses of community counts, towards analyses of population trends. To do the courses, please follow the course instructions step by step in the respective html-files of each course. 

## Prior steps
### Program installation

* RStudio Desktop (https://rstudio.com/products/rstudio/download/)  <br>
* current R-version (https://cran.r-project.org/bin/windows/base/)  <br>
<br>
If you are not familiar with R and RStudio, open RStudio and follow the steps shown here of how to write scripts in R: [Intro to RStudio](https://github.com/EcoDynIZW/EcoDynIZW.github.io/raw/teaching_23/img/teach/L1_Intro_RStudio.pdf)
<br>
<br>
If you are familiar with scripting in R in RStudio, here's our tip of the day of a cool feature in RStudio: use the rainbow parentheses option. For this, go to: Tools --> Global Options --> Code --> Display: tick rainbow parentheses. It helps you visually with  closing brackets correctly for function calls and loops.

### Folder setup
To ease access to data and script-functionality, we recommend that you use the same folder structure as we do. We chose the following folder structure for our courses, which you may adopt:
<br>

``` bash
├── d6_teaching_collection                 # root folder 
│   └── data_borneo                        # e.g., the Borneo data
│       └── geo_raster_current_asc         # geo data, raster ascii format, as in data_borneo
│       └── animal_data                    # animal observation data data_borneo
│   └── output                             # storage for files created during course
│   └── R                                  # store here all your scripts, i.e.
│       └── script_course1.R               # rmd-files with codes
│       └── script_course2.R
│   └── d6_teaching_collection.Rproj       # the R-project (recommended)
```
<br>

a) If you are not so familiar with R and want to do the steps 'by hand', create a main (root) folder named *d6_teaching_collection*, then create the subfolders (data, output, R) relative to this root-folder (= d6_teaching_collection). Create an R-project within this folder (e.g. *d6_teaching_collection.Rproj*. For this, open RStudio --> File --> New Project --> Existing directory: and then link it with the root folder).
<br><br>
b) Users familiar with R and RMarkdown could directly implement our [d6 workflow package](https://github.com/EcoDynIZW/d6) to make project setups easier and to handle code and projects in a reproducible way. If you chose this option, please read the ReadMe that appears on the github website and install the d6 package (with the options github= FALSE). This has the advantage that you have automatically created a root directory and an R-project. You can then load the data (e.g. data_borneo, provided in zip-files, see below) directly under the root directory. In the d6-package there are already start-rmd-scripts (= RMarkdown-scripts with yaml header -> open and execute with the symbol 'knitR'), which make the start easier. But you can also create your own  R-scripts, e.g. a new script for each course unit, which you put into the folder 'R'.
<br>  
For both options, a) and b), you need to download the data separately (link to zip.file below)
<br><br>
c) Or you simply clone our [github repository](https://github.com/EcoDynIZW/d6_teaching_collection) directly: https://github.com/EcoDynIZW/d6_teaching_collection . This has the advantage that it comes with some basic data. However, we still recommend that you make a copy of the R-scripts so that you can write your own comments. <br>
 

### Download course data
For the full course, we will provide you with additional data. Drag and drop the folders "data_borneo", "data_berlin", "data_move" from the provided zip files into the main folder (here: d6_teaching_collection). 

<br>  TODO --------------- provide link ----------------------


### Change decimal separator
from comma to point in your computer settings if you are working from a German PC, e.g. in Windows --> Settings --> Time and Region --> Region --> Advanced Settings --> decimal separator: change here to point.

### Change decimal separator
Each course comes with exercises as a learning control.


# Follow the courses
## Courses 1 and 2: Basic concepts in R & Spatial R

These courses contain the minimum knowledge for handling, manipulating and visualizing various data types in R (Course1: vectors, data.frames, lists; Course2: spatial data like raster and vector files). The second course builds on the concepts introduced in course 1. It is therefore recommended to start with course 1. Please note, that course 1 is **not** meant as a beginners course - a lot of great in-depth courses are out there, e.g. here
* https://cran.r-project.org/doc/contrib/Paradis-rdebuts_en.pdf or here <br>
* https://www.r-bloggers.com/list-of-free-online-r-tutorials/. 
<br>
Course 1 is rather a 'refresher' of the basic R concepts that are needed for all subsequent courses. In a nutshell, it goes through the [base R cheatsheet](https://iqss.github.io/dss-workshops/R/Rintro/base-r-cheat-sheet.pdf) . It is recommended to have the cheatsheets ready and make your own notes into a copy of our script.
<br>

----------------------TODO - correct linking----------
<br>
[Course1_IntroR](https://github.com/EcoDynIZW/EcoDynIZW.github.io/raw/teaching_23/img/teach/Course1_RIntro.html) <br>
[course2_SpatialR]()<br>
<br>



## Courses 3_a and 3_b Species distribution models 
### presence only  / MaxEnt

Please download MaxEnt here: https://biodiversityinformatics.amnh.org/open_source/maxent/
For MaxEnt you may still need to install a Java version. If you double-click the file maxent.jar, an  interface should appear


Course3_a_SDM

### repeated presence absence / occupancy models
Course3_b_occu

##Movement analysis
### telemetry data

Course4_MoveQ

##Biodiversity analysis
Course5_biodiv


