---
title: "Community structure and landscape-scale distribution of ground-dwelling mammals and birds in the Annamites: setting conservation priorities in a biodiversity hotspot"
description: ""
---

Snaring has led to the local extinction of numerous large- and medium-sized mammals and ground-dwelling birds, and pushed several Annamite endemic species to the brink of extinction. To protect the Annamites mammal and ground-dwelling bird community, it is imperative to collect data to inform anti-poaching initiatives and establish conservation baselines. I will conduct landscape-level systematic camera-trapping surveys in two forest blocks in the Annamites: Bidoup-Nui Ba National Park (NP) and the Kon Plong area. These surveys will provide robust data to assess the status and distribution of the faunal community within these areas and investigate which environmental and anthropogenic factors influence species occurrence. In addition, I will combine these data with data collected by Leibniz-IZW since 2014 in other parts of Annamites landscape to study how the loss of larger mammals (termed defaunation) contributes to ecosystem cascade effects that impact smaller mammal and ground bird species. Finally, the combined data will be used to identify biodiversity hotspots for Annamites endemics across the entire Annamite ecoregion.

An Nguyen