---
title: 'roadless-areas world 2016'
categories:
  - World
  - 1km
  - esri:54009
  - '2016'
author:
  - name: Moritz Wenzler-Meya

    affiliation: IZW Berlin
    affiliation_url: https://ecodynizw.github.io/EcoDynIZW
date: '2026-01-26'
output:
  distill::distill_article:
    self_contained: false
    toc: true
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE,
dev = 'ragg_png', fig.width = 9, fig.height = 6, dpi = 250, retina = 1)

Sys.setlocale('LC_TIME', 'C')

library(patchwork)

`%>%` <- magrittr::`%>%`

ggplot2::theme_set(ggplot2::theme_void())
ggplot2::theme_update(
  legend.position = 'bottom',
  legend.key.width = ggplot2::unit(3.5, 'lines'),
  legend.key.height = ggplot2::unit(.5, 'lines'),
  plot.margin = ggplot2::margin(rep(10, 4)),
  plot.title = ggplot2::element_text(hjust = .5, face = 'bold')
)
```



```{r data-impor}

# get path
path <-
    paste0(ifelse(dir.exists('T:/wenzler') == T, 'T:/wenzler',
    ifelse(dir.exists('C:/PopDynCloud') == T, 'C:/PopDynCloud', 'E:/PopDynCloud')),  '/',  'GeoData/data/world/roadless-areas_world_2016_1km_54009_tif')

meta <-
      utils::read.csv(list.files(path, pattern = '.csv$', recursive = TRUE, full.names = TRUE)) %>%
  dplyr::mutate(dplyr::across(dplyr::everything(), as.character))

```

```{r data-table}
meta_gt <- gt::gt(meta %>%
  tidyr::pivot_longer(
    cols = dplyr::everything(),
    names_to = 'column',
    values_to = 'input'
  ))
```

```{r map}
p_map <-
 readRDS(paste0(ifelse(dir.exists('T:/wenzler') == T, 'T:/wenzler',
    ifelse(dir.exists('C:/PopDynCloud') == T, 'C:/PopDynCloud', 'E:/PopDynCloud')),  '/',  'GeoData/data/world/roadless-areas_world_2016_1km_54009_tif/roadless-areas_world_2016_1km_54009_tif' ,'.rds'))

```

```{r plot, layout='l-screen'}
p_map
meta_gt
```


<details><summary>Session Info</summary>

```{r sessionInfo}
## DO NOT REMOVE!
## We store the settings of your computer and the current versions of the
## packages used to allow for reproducibility
Sys.time()
#git2r::repository() ## uncomment if you are using GitHub
sessionInfo()
```

</details>
