---
title: "A Collection of Different Spatial Data Sources"
description: |
 Learn how to search and download spatial data from various sources and in different resolutions and scales.
categories:
  - Tuturial
  - spatial data
  
author:
  - name: Moritz Wenzler-Meya
    affiliation: IZW Berlin
    affiliation_url: https://ecodynizw.github.io/EcoDynIZW
date: 2023-06-26
output:
  distill::distill_article:
    self_contained: false
    toc: true
draft: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

A lot of spatial data is easily and freely available, but sometimes it needs a bit more afford to get them like creating an account and selecting data from different time periods and scales. Below you find a list of data sources, sorted by the region covered, and some further information about how to access and download the data.

## Berlin

### FIS-Broker

[https://fbinter.stadt-berlin.de/fb/index.jsp](https://fbinter.stadt-berlin.de/fb/index.jsp)

- open-access
- the [{d6berlin} package](https://ecodynizw.github.io/posts/d6berlinpackage/) provides utility functions to download FIS-Broker data: `download_fisbroker_wfs` (vector data) and `download_fisbroker_atom` (raster data)


## Germany

### BKG

[https://gdz.bkg.bund.de/index.php/default/digitale-geodaten.html](https://gdz.bkg.bund.de/index.php/default/digitale-geodaten.html)

- partly open-access
- for access to all sources you have to pay or be part of a federal agency
- some data can be directly downloaded, other have to be processed and are provided after a certain time


## Europe

### Copernicus

[https://land.copernicus.eu/pan-european](https://land.copernicus.eu/pan-european)

- data are freely available but sign-up required
- direct download links are provided for most of the data sets
- only raster data


## World wide

### Single data sets

You'll find some datasets on most of the websites in this post, but as far as we know there is no such a side hosting more than one world dataset.

### Archives with temporal and spatial tiles

### Earthexplorer

[https://earthexplorer.usgs.gov/](https://earthexplorer.usgs.gov/)

- data are freely avaiable but sign-up required
- mostly open-access
- only raw raster data
- provides Landsat, MODIS, VIIRS and many more sources

### ESPA

[https://espa.cr.usgs.gov/](https://espa.cr.usgs.gov/)

- same account as for earthexplorer
- provides satellite image products such as NDVI and NDSI
- Landsat, MODIS and VIIRS data only
