---
title: "Manage Camera Trap Data in R"
description: |
  Learn how to use the {camtrapR} R package for streamlined and flexible camera trap data management. It should be most useful to researchers and practitioners who regularly handle large amounts of camera trapping data.
preview: https://raw.githubusercontent.com/EcoDynIZW/EcoDynIZW.github.io/main/img/wiki/hex-camtrapr.png
categories:
  - tutorial
  - rstats
  - camera trapping
  - data management
author:
  - name: Jürgen Niedballa
    affiliation: IZW Berlin
    affiliation_url: https://ecodynizw.github.io/
date: 05-23-2022
output:
  distill::distill_article:
    self_contained: false
    toc: true
---

The [`{camtrapR}` R package](https://github.com/jniedballa/camtrapR) simplifies camera trap data management in R. 

## Installation

You can install the release version of `{camtrapR}` from CRAN:

```{r, eval=FALSE, echo=TRUE}
install.packages("camtrapR")
```

## Exiftool

Numerous important `{camtrapR}` functions read EXIF metadata from JPG images (and videos). This is done via `Exiftool`, a free and open-source sofware tool developed by Phil Harvey and available for Windows, MacOS and Linux.

To make full use of `{camtrapR}`, you will need `Exiftool` on your system. You can download it from the `Exiftool` homepage and follow the installation instruction in vignette 1.

You may not need `Exiftool` if you do not work with image files, but only use `{camtrapR}` to create input for occupancy or spatial capture-recapture models from existing record tables.

See the [article in Methods in Ecology and Evolution](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.12600) for an overview of the package. The five vignettes provide examples for the entire workflow.
Citation


