---
title: 'Europe raw raster data'
categories:
  - Europe
  - Raster
author:
  - name: Moritz Wenzler-Meya

    affiliation: IZW Berlin
    affiliation_url: https://ecodynizw.github.io/EcoDynIZW
date: 2022-11-25
output:
  distill::distill_article:
    self_contained: false
    toc: true
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE,
dev = 'ragg_png', fig.width = 9, fig.height = 6, dpi = 250, retina = 1)

Sys.setlocale('LC_TIME', 'C')

library(patchwork)

`%>%` <- magrittr::`%>%`

ggplot2::theme_set(ggplot2::theme_void())
ggplot2::theme_update(
  legend.position = 'bottom',
  legend.key.width = ggplot2::unit(3.5, 'lines'),
  legend.key.height = ggplot2::unit(.5, 'lines'),
  plot.margin = ggplot2::margin(rep(10, 4)),
  plot.title = ggplot2::element_text(hjust = .5, face = 'bold')
)
```


<details><summary>100m resolution</summary>
```{r}
"meta-data grassland 100m 2018"
"meta-data grassland 100m 2015"
```
</details>

<details><summary>20m resolution</summary>

  <details><summary>2018</summary>
```{r}
"meta-data grassland 20m 2018"
```
  </details>

  <details><summary>2015</summary>
```{r}
"meta-data grassland 20m 2015"
```
  </details>

  <details><summary>2012</summary>
```{r}
"meta-data grassland 20m 2012"
```
  </details>

</details>

<details><summary>10m resolution</summary>
```{r}
"meta-data grassland 10m 2012"
```
</details>

<details><summary>Session Info</summary>

```{r sessionInfo}
## DO NOT REMOVE!
## We store the settings of your computer and the current versions of the
## packages used to allow for reproducibility
Sys.time()
#git2r::repository() ## uncomment if you are using GitHub
sessionInfo()
```

</details>

