---
title: "Raster Template"
description: |
  Learn how to use a raster template from the `{d6geodata}` package und how to multiple/expand it. In the end we will rasterize a shapefile with the raster have a look into different extraction functions.
categories:
  - Tutorial
  - Spatial
author:
  - name: Moritz Wenzler-Meya
    affiliation: IZW Berlin
    affiliation_url: https://ecodynizw.github.io/EcoDynIZW
date: 2023-06-28
output:
  distill::distill_article:
    self_contained: false
    toc: true
draft: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) ## keep this, add other settings if needed
```

## Setup {#setup}

```{r}
#remotes::install_github("EcoDynIZW/d6geodata")
library(d6geodata)
library(terra)
library(ggplot2)
library(sf)
library(patchwork)
```


## get template {#template}

```{r template}
temp <- d6geodata::temp_ras(1000)
values(temp) <- 1

p1 <- d6geodata::plot_qualitative_map(temp)
p1
```

## expand raster {#expand}

```{r}
temp_exp_all <- terra::extend(x = temp, 
                    y = 10,
                    fill = 2)

p2 <- d6geodata::plot_qualitative_map(temp_exp_all)

temp_exp_2_sides <- terra::extend(x = temp, 
                    y = c(10, 0),
                    fill = 2,
                    )
p3 <- d6geodata::plot_qualitative_map(temp_exp_2_sides)

temp_exp_1_sides <- terra::extend(x = temp, 
                    y = c(10, 0, 0, 0),
                    fill = 2,
                    )
p3 <- d6geodata::plot_qualitative_map(temp_exp_2_sides)
```

rasterize

```{r plot}
d6geodata::plot_qualitative_map(temp_exp)
```

Please knit the whole document in the end, to test if it is working!

